### ISSUE TITLE
GPGTools Suite Installer on Big Sur

### ISSUE THREAD

**Issue by bnavigator** [Free-GPGMail/Free-GPGMail#7]
Hey guys,
sorry for intruding but here's a couple of issues:

@bnavigator: in your latest release of [Free GPG Mail 2020.1 for Big Sur](https://github.com/bnavigator/Free-GPGMail/releases/tag/v2020.1b) you link the official GPGTools Suite 2020.1 Installer from gpgtools.org.
On Big Sur the installer actually fails, throwing a weird error about macOS versions. The installer checks for minor macOS 10 versions, assuming Big Sur is supposed to be 10.16. Dunno, maybe that was the case with Big Sur beta versions, never tested those. But as of now Big Sur is macOS 11.x.
After expanding the installer .pkg, tweaking the versions checks and flattening the .pkg again i was able to install the official 2020.1 version.
Following your installation instructions i deleted the GPGMailLoader.mailbundle and placed Free-GPGMail_4.mailbundle in ~/Library/Mail/Bundles/

But after enabling the plugin in mail i get this:
<img width="409" alt="Bildschirmfoto 2020-11-22 um 10 57 26" src="https://user-images.githubusercontent.com/5215809/99900985-8a8a0000-2cb3-11eb-9c67-6ca27aade7a8.png">
Yeah right, that's german. It says it can't verify the developer, it may be malware, craps it's pants and gives two options:

1. trash the plugin.
2. cancel.

In system preferences -> security i repeatedly clicked "open it anyway". To no avail.
So i hit cancel. Then this happens:
<img width="409" alt="Bildschirmfoto 2020-11-22 um 10 57 43" src="https://user-images.githubusercontent.com/5215809/99901027-e9e81000-2cb3-11eb-8db0-cbe2c5f1f742.png">
It says the plugin is not compatible and can't be used.

Any advice on how you guys got this working on big sur? Pretty please :)

_Originally posted by @dleicht in https://github.com/bnavigator/Free-GPGMail/issues/5#issuecomment-731726609_

**Comment by bnavigator** [comment]
@jpr5 any idea? Does it only work for you because you can sign your own bundles locally?

Remember, I don't even own a Mac :clown_face:

**Comment by bnavigator** [comment]
["Can't you just right click?"](https://lapcatsoftware.com/articles/unsigned.html)

**Comment by dleicht** [comment]
> "Can't you just right click?"

Unfortunately not. If i right-click open the .mailbundle i get a prompt to choose a program to open it with. If i choose mail it just copies the .mailbundle file into a new email.
If a rename the .mailbundle to .app and right-click open it, i get an error like "permission denied".
;(

**Comment by bnavigator** [comment]
Yeah, that obviously only works for app installations not for mailbundles.

Are you able to use XCode to build the bundle yourself?

@jpr5, is it possible to add a `codesign` call to the workflow?

**Comment by sT331h0rs3** [comment]
I managed to bypass this by temporarily disabling Gatekeeper:
* `sudo spctl --master-disable`;
* enable plugin in Mail application;
* `sudo spctl --master-enable`.

**Comment by jpr5** [comment]
Finally getting a chance to respond to this.

- As I already had the GPGTools installed, I didn't encounter installer errors for it.  It's a bummer this is the case.
- You get the "incompatible plugin" when the UUID in `/System/Applications/Mail.app/Contents/Info.plist` under `PluginCompatibilityUUID` doesn't match a corresponding entry in `Free-GPGMail/Contents/Info.plist` under `SupportedXXXPluginCompatibilityUUIDs`, where XXX is `10.15` on Catalina and `11.0` on Big Sur.
- It appears that I missed something important here, due to the fact that I have Gatekeeper disabled on my development machine.  Specifically, that `~/Library/Mail/Bundles` has become a protected directory now (`ls ~/Library/Mail` now produces `ls: .: Operation not permitted`).  Sorry for this miss.

I'm going to do a little more research.

**Comment by jpr5** [comment]
@bnavigator It doesn't look like this is a matter of codesigning; the directories the plugin needs to be copied into are all protected now.  I figure it's a matter of gaining an entitlement of some sort, hopefully with a user prompt for permission.  Still digging around.

As noted earlier, if you disable gatekeeper altogether for a brief moment (`spctl`), you can get it copied in.  I suppose this should be outlined visibly as a suitable workaround until we figure out the Right Way to do it.

**Comment by bnavigator** [comment]
> * You get the "incompatible plugin" when the UUID in `/System/Applications/Mail.app/Contents/Info.plist` under `PluginCompatibilityUUID` doesn't match a corresponding entry in `Free-GPGMail/Contents/Info.plist` under `SupportedXXXPluginCompatibilityUUIDs`, where XXX is `10.15` on Catalina and `11.0` on Big Sur.

But I thought 14164d45bc087620a8d54ad8ff1e3e97c6d8de52 takes care of exactly that? Or ist the message also displayed because the permission to read `Info.plist` was denied?

**Comment by bnavigator** [comment]
> As noted earlier, if you disable gatekeeper altogether for a brief moment (`spctl`), you can get it copied in. I suppose this should be outlined visibly as a suitable workaround until we figure out the Right Way to do it.

I can add that to the Release Notes and to the Readme.

What about adjusting the installer checks in the GPGSuite? Could you provide any instructions for these?

**Comment by jpr5** [comment]
@bnavigator 

> > * You get the "incompatible plugin" when the UUID in `/System/Applications/Mail.app/Contents/Info.plist` under `PluginCompatibilityUUID` doesn't match a corresponding entry in `Free-GPGMail/Contents/Info.plist` under `SupportedXXXPluginCompatibilityUUIDs`, where XXX is `10.15` on Catalina and `11.0` on Big Sur.
> 
> But I thought [14164d4](https://github.com/bnavigator/Free-GPGMail/commit/14164d45bc087620a8d54ad8ff1e3e97c6d8de52) takes care of exactly that? Or ist the message also displayed because the permission to read `Info.plist` was denied?

It did.  The fact that the person encountered it implies PEBKAC.

**Comment by bnavigator** [comment]
I don't think so. He mentions that the message appears after this:

> In system preferences -> security i repeatedly clicked "open it anyway". To no avail.
> So i hit cancel. Then this happens:

So it is a sign of not being able to read the `Free-GPGMail/Contents/Info.plist` at all. Not that it is not there.

**Comment by jpr5** [comment]
> > As noted earlier, if you disable gatekeeper altogether for a brief moment (`spctl`), you can get it copied in. I suppose this should be outlined visibly as a suitable workaround until we figure out the Right Way to do it.
> 
> I can add that to the Release Notes and to the Readme.
> 
> What about adjusting the installer checks in the GPGSuite? Could you provide any instructions for these?

I'm honestly at a loss here.. The Way this sort of thing is handled these days is with specific entitlements that are assigned to Apps.  Specifically, we're talking about disk access entitlements.  There are entitlements for specific directories, like `Downloads` or `Desktop`, and then there's one for `Full Disk Access` that I've seen many app developers go for (Apple discourages this however since it loosens the protections).  

The issue here is we're essentially talking about permissions of the app you're running the copy command from.  In the common case, here we're talking about `Terminal.app`.  And we probably shouldn't mess with its entitlements.

What I've figured out is that you _can_ use `Finder.app` to deposit the bits in place.  It will prompt for the root password, and then complete.  

Then I went in to Mail / Settings, Manage Plug-ins, and enabled the new plugin, then Allow Access and Apply & Restart.

THEN I see this error: https://take.ms/pCtVI
The consequence of which is then: https://take.ms/7kgpE

Which to me can probably be solved with a codesigning.  But that means whoever is doing the build needs to have a developer account (I do; do you?).

**Comment by bnavigator** [comment]
I don't. There are some instruction pages how to add certificates and keys to the Github workflows, but I am not sure whether this is suitable for our needs.

Other sources mention ad-hoc signing without any pre-installed key from a developer account. I am not familiar with the procedures, though. Is ad-hoc signing only possible for runtimes built on the same machine that it is run on, or would this be okay for our setup?

And then there is the mention of the new ARM Macs having a stricter rule for signatures.

**Comment by jpr5** [comment]
I don't believe ad-hoc signing will actually work for this circumstance - IIRC that's for local/developer-type stuff where you want the systems to all work but you're iterating and aren't ready to incorporate Apple's release systems into the mix.  Besides, Apple wants every distributed application/bundle of bits to be signed by a known entity; allowing edge cases for this defeats the purpose entirely.

If there's more restrictions on ARMs, I'd expect them to be about underlying crypto and not about logical entitlements.  It's still Big Sur underneath, doesn't make sense to me for them to fork the security model for a different CPU.

As for signing, I need time to figure out what it would take to sign the binaries.  Just thinking ahead, in the end it may make sense for us to set up a gofundme or something just to cover the small (~$100) annual cost of a developer/org account, and sign with those.  This is what [Emacs](https://emacsformacosx.com/) does.

**Comment by jpr5** [comment]
@bnavigator To be clear, the README mentions `spctl` as though it should work; at this point I don't think this is the case.  I have to test this back at home to be sure, but I think it only worked for me on my dev machine because I had [SIP disabled entirely](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).  

Suggest updating the README to reflect that reality for the time being, until we have the codesigning shiz figured out.

**Comment by bnavigator** [comment]
Okay, I will not merge #8 until we have a clear picture.

**Comment by bnavigator** [comment]
Note from "commercial" GPG Tools:

https://gpgtools.tenderapp.com/

> ⚠️ If you rely on GPG Mail do not install macOS 11 Big Sur for now.
GPG Suite 2020.2 with GPG Mail 5 for macOS Big Sur will be out next week! ⚠️

**Comment by bnavigator** [comment]
If you can't execute @dleicht's approach
> After expanding the installer .pkg, tweaking the versions checks and flattening the .pkg again i was able to install the official 2020.1 version.

you might be able to install the latest GPG Tools nightly [they say it works for Big Sur](https://gpgtools.tenderapp.com/discussions/feedback/16185-is-it-possible-to-install-gpg-suite-on-macos-big-sur-without-mail-plugin):
https://releases.gpgtools.org/nightlies/

And replace GPGMail with Free GPG Mail afterwards, applying @sT331h0rs3's suggestion (https://github.com/bnavigator/Free-GPGMail/issues/7#issuecomment-732293174)

**Comment by dleicht** [comment]
> If you can't execute @dleicht's approach
> 
> > After expanding the installer .pkg, tweaking the versions checks and flattening the .pkg again i was able to install the official 2020.1 version.
> 
> you might be able to install the latest GPG Tools nightly [they say it works for Big Sur](https://gpgtools.tenderapp.com/discussions/feedback/16185-is-it-possible-to-install-gpg-suite-on-macos-big-sur-without-mail-plugin):
> https://releases.gpgtools.org/nightlies/
> 
> And replace GPGMail with Free GPG Mail afterwards, applying @sT331h0rs3's suggestion ([#7 (comment)](https://github.com/bnavigator/Free-GPGMail/issues/7#issuecomment-732293174))

I tried the nightly before and it fails for the same reason. Look at the age of that thing. They prolly developed it with a pre release version of big sur and maybe it was 10.16 back then.
The installer package is not a big issue tho, i can provide a diff so everyone can build their own. But it's only one file that needs to be changed and there's no signing involved, so i can just provide my working installer, if you like.



> I managed to bypass this by temporarily disabling Gatekeeper:
> 
> * `sudo spctl --master-disable`;
> * enable plugin in Mail application;
> * `sudo spctl --master-enable`.

Will give this a try.

**Comment by jpr5** [comment]
Exciting though that they say it'll be out in a week.

That said, *last* time they were late by _months_ post-OS release...

Fingers crossed....

**Comment by bnavigator** [comment]
Yeah, we don't even know when that message was written. The article which they link to is 2 weeks old.

So sad that Mac users don't get proper PGP software support by the FOSS community but you all depend on a shady software company from Vienna who tries to coerce people into paying for poorly maintained software.

**Comment by dleicht** [comment]
In order to make the installer work you can simply apply this patchfile to the "Distribution" file inside the package:
[GPG_Suite_2020.1.patch.zip](https://github.com/bnavigator/Free-GPGMail/files/5586676/GPG_Suite_2020.1.patch.zip)

Or you just use my already patched installer:
[GPG_Suite-2020.1-patched.pkg](https://drive.google.com/file/d/193gK73vbv4jHCEoTo_phKTXw7SOe7flC/view?usp=sharing)
SHA256 = 9beb20c51b6707d5136d9d3f2b7a0f9ca7a1e9b4a969fd5af659ed0f6026dd51

Okay, so disabling gatekeeper enabled me to get the .mailbundle going:
<img width="796" alt="Bildschirmfoto 2020-11-24 um 01 25 23" src="https://user-images.githubusercontent.com/5215809/100031397-d644c280-2df5-11eb-9b4c-cf8981493fcc.png">
However: i can send encoded emails, but mail can't automatically decode them, giving this error about missing folder access permissions:
<img width="562" alt="Bildschirmfoto 2020-11-24 um 01 33 17" src="https://user-images.githubusercontent.com/5215809/100031485-0db36f00-2df6-11eb-9bbf-5d37a6445360.png">
After all GPG Mail is not present in the system preferences GPG Suite overview:
<img width="875" alt="Bildschirmfoto 2020-11-24 um 01 32 44" src="https://user-images.githubusercontent.com/5215809/100031603-53703780-2df6-11eb-8ea0-7e236f8e9187.png">
Is this considered normal?

**Comment by dleicht** [comment]
Never mind the access permissions error. After giving full disc access to GPG-Services in system preferences that was fixed.
But still mail will not automatically decrypt emails, it just shows the encrypted attachments.

**Comment by jpr5** [comment]
Yeah, so I'm gonna have to mea culpa here and say it doesn't work completely in the typical/average case.  

I'm gonna guess that the GPG Tools team didn't anticipate the tightening of restrictions on file system locations and thus have a lot more work ahead of them than they expected in order to make things work again.  Guess they don't have a habit of downloading OS betas and making sure their stuff works ahead of time.  Sigh.

At this point, we're either patching their code with fixes while they do the same in parallel, _or_ we're waiting for them to release a working version.

Though, last time they seriously dragged ass on releasing the source after releasing the working package.

**Comment by dleicht** [comment]
@sT331h0rs3 does GPG Mail completely work for you then? You didn't seem to have any remaining issues?

**Comment by sT331h0rs3** [comment]
@dleicht, unfortunately, I had no chance to check the encryption and decryption yesterday, just managed to bypass the permission issue.
I assume we should wait for the GPG Suite update (and its source code, which usually comes even later) to have it working on Big Sur.

**Comment by bnavigator** [comment]
Thank you @dleicht!

> In order to make the installer work you can simply apply this patchfile to the "Distribution" file inside the package:
> [GPG_Suite_2020.1.patch.zip](https://github.com/bnavigator/Free-GPGMail/files/5586676/GPG_Suite_2020.1.patch.zip)

So editing those two lines would be enough during installation?

> Or you just use my already patched installer:
> [GPG_Suite-2020.1-patched.pkg](https://drive.google.com/file/d/193gK73vbv4jHCEoTo_phKTXw7SOe7flC/view?usp=sharing)
> SHA256 = 9beb20c51b6707d5136d9d3f2b7a0f9ca7a1e9b4a969fd5af659ed0f6026dd51

Another random unsinged binary downloaded from the internet. :)


> After all GPG Mail is not present in the system preferences GPG Suite overview:
> Is this considered normal?

You removed the original GPGMail.mailbundle, didn't you?

**Comment by dleicht** [comment]
> Thank you @dleicht!
> 
> > In order to make the installer work you can simply apply this patchfile to the "Distribution" file inside the package:
> > [GPG_Suite_2020.1.patch.zip](https://github.com/bnavigator/Free-GPGMail/files/5586676/GPG_Suite_2020.1.patch.zip)
> 
> So editing those two lines would be enough during installation?

Yes sir. The original installer checked if your macOS version was 10.15 or 10.16.
There is no such thing as macOS 10.16.
With the patch applied the installer checks if your macOS version is 10.x or 11.x

> 
> > Or you just use my already patched installer:
> > [GPG_Suite-2020.1-patched.pkg](https://drive.google.com/file/d/193gK73vbv4jHCEoTo_phKTXw7SOe7flC/view?usp=sharing)
> > SHA256 = 9beb20c51b6707d5136d9d3f2b7a0f9ca7a1e9b4a969fd5af659ed0f6026dd51
> 
> Another random unsinged binary downloaded from the internet. :)

Most Apple customers may not be used to diff and patch. Just wanted to provide this to make things easier.

> 
> > After all GPG Mail is not present in the system preferences GPG Suite overview:
> > Is this considered normal?
> 
> You removed the original GPGMail.mailbundle, didn't you?

Yes, i did. I thought your .mailbundle might also provide that part.

**Comment by bnavigator** [comment]
GPG Tools 2020.2 is out, but no source code archive.

**Comment by jpr5** [comment]
Not only is it out, but it's a *paid* upgrade.  That means if you paid for it already, you have to pay again.

**Comment by palxex** [comment]
With patched installer and manual modify info.plist got encryption works, but decryption not work. 
Big Sur 11.0.1 Mail 14.

**Comment by palxex** [comment]
@bnavigator just tested new built Free-GPGMail_5.mailbundle, after manually adds Supported11.0PluginCompatibilityUUIDs, it could load and decryption works. But activation fails, reports "Support Plan Activation Failed: The entered activation code is invalid. Please check the entered information and try again.".

**Comment by bnavigator** [comment]
> after manually adds Supported11.0PluginCompatibilityUUIDs, it could load and decryption works.

Wait, they forgot to add the UUID that they support mail.app in Big Sur ????

**Comment by bnavigator** [comment]
> But activation fails, reports "Support Plan Activation Failed: The entered activation code is invalid. Please check the entered information and try again.".

Okay, I will have to check the code for changed checks for an active support plan and activation procedures. Thanks. Please put addtional comments regarding GPGMail_5 into #10.
