### ISSUE TITLE
Apple Mail 13.3 beta has new UUID

### ISSUE THREAD

**Issue by Heliophon** [Free-GPGMail/Free-GPGMail#77]
Hi.
Apple Mail in the current 13.3beta 2 obviously has a new UUID (281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE). I've tried editing the Info.plist in the freegpgmail bundle but I can't get the bundle to work. Can someone help?
Sincerely,
Heliophon

**Comment by Jadeye-hu** [comment]
Hey @Heliophon!

This is how I was able to solve this issue.

1. Download the source and extract it to a folder.
2. Edit the Info.plist by adding the new UUID – I added it as a second UUID while leaving the old one there as well:
```
<key>Supported13.3PluginCompatibilityUUIDs</key>
	<array>
		<string>890E3F5B-9490-4828-8F3F-B6561E513FCC</string>
		<string>281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE</string>
	</array>
```
3. Save the file.
4. Open Terminal, navigate to the Source folder and make the updated bundle:
`make GPGMail_7`
5. Copy the built bundle to ~/Library/Mail/Bundles and overwrite the old version.
6. Quit Mail.
7. Go back to Terminal and run this command – because of sudo you'll need to enter your macOS password:
`sudo spctl --add ~/Library/Mail/Bundles/Free-GPGMail_7.mailbundle`
8. Launch Mail, open its settings, and on the General tab click on the Manage Plug-ins… in the lower left corner.
9. Put in the checkmark next to Free-GPGMail_7.mailbundle, then select Apply and Restart Mail – you will receive several confirmation dialogs, allow all.
10. When Mail restarts Free-GPGMail_7 should now work!

**Comment by Heliophon** [comment]
Hi Jadeye-hu,

Worked like a charm, thank you very much

Best wishes,
H.

**Comment by bnavigator** [comment]
Thanks for the heads up. I have added the UUID to the sources in #78 and if it builds, I'll merge and make a new release.

**Comment by bnavigator** [comment]
@Heliophon, @Jadeye-hu could you please test [Free-GPGMail_7_signed.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/10886209/Free-GPGMail_7_signed.mailbundle.zip)?

**Comment by Jadeye-hu** [comment]
@bnavigator Tested it, and it works fine. :)

<img width="782" alt="Screenshot 2023-03-03 at 23 51 56" src="https://user-images.githubusercontent.com/95970523/222848366-14adfb9f-dfe3-4ca6-9312-131063fc4f47.png">

**Comment by Heliophon** [comment]
@bnavigator: here also everything works fine
Thanks,
Best wishes
H.

**Comment by Ubsefor** [comment]
> @Heliophon, @Jadeye-hu could you please test [Free-GPGMail_7_signed.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/10886209/Free-GPGMail_7_signed.mailbundle.zip)?

Nice, but could you please fix the releases tab and attach this file instead of debug symbols? :)

**Comment by bnavigator** [comment]
Fixed. Sorry about that.

**Comment by Ubsefor** [comment]
> Fixed. Sorry about that.

Np, thanks for that!

**Comment by jameswillhoite** [comment]
There is a new GPG Mail 2023.2 that adds this UUID. Is it okay to upgrade to that version since this new UUID was already added?

**Comment by bnavigator** [comment]
If you have a paid plan or want to check out the trial :laughing:

**Comment by bnavigator** [comment]
> https://gpgtools.com/releases/gpgsuite/2023.2/release-notes.html

> Adapts GPG Mail 7 to changes of Mail in macOS 13.3
> Adds the new mailbundle UUID introduced in macOS 13.3 to GPG Mail 7

These are the only entries in the changelog. If that is all, we don't need an update in Free-GPGMail, since we already have the UUID in 2023.1

**Comment by jameswillhoite** [comment]
That's what I was thinking. Those were the only changes I saw too. But wanted to double check. Thanks.
